// src/utils/eventTypes.js
export const AppEvents = {
  // 命令 & 请求
  OPEN_IMAGE: 'OPEN_IMAGE',
  PARSE_REQUEST: 'PARSE_REQUEST',
  ASSIST_LABELING_REQUEST: 'ASSIST_LABELING_REQUEST',
  SELECT_LAYER: 'SELECT_LAYER',
  SET_LABELING_MODE: 'SET_LABELING_MODE',
  TOGGLE_LABELING_DIALOG: 'TOGGLE_LABELING_DIALOG',

  // 通知 (可选，但推荐)
  SHOW_ERROR: 'SHOW_ERROR',
  SHOW_SUCCESS: 'SHOW_SUCCESS',
  SHOW_WARNING: 'SHOW_WARNING',
  SHOW_INFO: 'SHOW_INFO',
}